const test=require("node:test");
const assert=require("node:assert/strict");
const fs=require("node:fs");
const vm=require("node:vm");
const source=fs.readFileSync("platform/panel.js","utf8");
function panelApi(){const ctx={window:{},structuredClone:global.structuredClone,Math,Number,String,Array,Map,Set,Error};vm.createContext(ctx);vm.runInContext(source,ctx);return ctx.window.VoltProPanel}
test("panel model creates an enclosure and DIN rail defaults",()=>{const api=panelApi(),p=api.create();assert.equal(p.rails.length,1);assert.equal(p.rails[0].id,"R1");assert.equal(p.rails[0].length,18);assert.equal(p.enclosure.ipRating,"IP40")});
test("panel device placement, repositioning and removal work",()=>{const api=panelApi(),p=api.create();api.place(p,{id:"P1",type:"breaker",label:"QF1",railId:"R1",position:0,width:36});api.move(p,"P1",{position:36});assert.equal(p.items[0].position,36);api.remove(p,"P1");assert.equal(p.items.length,0)});
test("layout validation reports overlaps, duplicate IDs and rail overflow",()=>{const api=panelApi(),p=api.create();api.place(p,{id:"P1",type:"breaker",label:"QF1",railId:"R1",position:0,width:36});p.items.push({id:"P2",type:"relay",label:"K1",railId:"R1",position:18,width:36});p.items.push({id:"P2",type:"relay",label:"K2",railId:"R1",position:324,width:36});const result=api.validate(p);assert.equal(result.valid,false);assert.ok(result.errors.some(x=>x.includes("Overlap")));assert.ok(result.errors.some(x=>x.includes("Duplicate placement ID")));assert.ok(result.errors.some(x=>x.includes("exceeds")))});
test("panel-only accessories are identified as warnings, not electrical components",()=>{const api=panelApi(),p=api.create();api.place(p,{id:"P1",type:"terminal-strip",label:"X1 terminal strip",railId:"R1",position:0,width:36,kind:"accessory"});const r=api.validate(p);assert.equal(r.valid,true);assert.ok(r.warnings.some(x=>x.includes("panel-only")));assert.equal(r.deviceCount,0)});
test("additional rails have unique IDs and can hold more placements",()=>{const api=panelApi(),p=api.create();api.addRail(p,{id:"R2",length:24});assert.equal(p.rails.length,2);assert.throws(()=>api.addRail(p,{id:"R2",length:18}),/Duplicate rail id/)});

test("panel layout is persisted by project save/load paths",()=>{const simulator=fs.readFileSync("simulator.js","utf8");assert.match(simulator,/panel:window\.VoltProPanel\?\.create\?\.\(S\.panel\|\|\{\}\)/);assert.match(simulator,/S\.panel=window\.VoltProPanel\?\.create\?\.\(x\.panel\|\|\{\}\)/)});
test("BOM and engineering documentation include panel rails and accessories",()=>{const bomCtx={window:{}};vm.createContext(bomCtx);vm.runInContext(fs.readFileSync("platform/bom.js","utf8"),bomCtx);const docsCtx={window:{VoltProPanel:{validate:()=>({valid:true,errors:[],warnings:[]})}}};vm.createContext(docsCtx);vm.runInContext(fs.readFileSync("platform/documentation.js","utf8"),docsCtx);const p={components:[{id:"QF1",type:"breaker",props:{rating:6}}],wires:[],panel:{width:600,height:400,enclosure:{label:"DB1",ipRating:"IP40"},rails:[{id:"R1",label:"DIN rail 1",length:18}],items:[{id:"P-QF1",componentId:"QF1",type:"breaker",label:"QF1",railId:"R1",position:0,width:36}],ducts:[{id:"D1",label:"D1",fill:.35}],terminalStrips:[{id:"X1",label:"X1",count:12}]}};const rows=bomCtx.window.VoltProBOM.build(p);assert.ok(rows.some(x=>x.reference==="DIN rail TS 35"));assert.ok(rows.some(x=>x.reference==="Cable duct"));assert.ok(rows.some(x=>x.reference==="Terminal strip"));const md=docsCtx.window.VoltProDocs.markdown(p);assert.ok(md.includes("QF1"));assert.ok(md.includes("DIN rails"));assert.ok(md.includes("Cable ducts: 1"))});
