(()=>{"use strict";
const esc=x=>String(x??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const templates=[
["Protected DC Lamp","DC Basics","Build a fused low-voltage lighting circuit.","battery,fuse,switch,lamp"],
["Series Resistor Study","DC Basics","Explore the effect of series resistance on a load.","battery,resistor,resistor,lamp"],
["LED Indicator","Electronics","Explore a current-limited LED indicator.","battery,resistor,led,switch"],
["RC Learning Circuit","Electronics","Inspect resistance and capacitance parameters.","battery,resistor,switch,capacitor"],
["Inductive Load","Electronics","Explore an inductive load arrangement.","acsource,inductor,resistor,switch"],
["Diode Protection","Electronics","Study a diode in a protected DC path.","battery,fuse,diode,resistor"],
["Fuse Protected Motor","Protection","Place a fuse upstream of a switched motor load.","battery,fuse,switch,motor"],
["MCB Protected Heater","Protection","Arrange a breaker and resistive load.","acsource,breaker,switch,heater"],
["Relay Control","Control","Explore a relay-controlled indicator circuit.","battery,switch,relay,lamp"],
["Contactor Motor Concept","Industrial Control","Arrange protection, contactor and motor blocks.","battery,fuse,contactor,motor"],
["Motor Load Study","Industrial Control","Change the simplified motor resistance model.","battery,breaker,switch,motor"],
["Buzzer Alarm","Control","Create a switched audible-indicator circuit.","battery,fuse,switch,buzzer"],
["Heater Control","Industrial Control","Study a switched resistive load.","acsource,breaker,switch,heater"],
["AC Measurement","Measurement","Arrange an AC source, instrument and load.","acsource,multimeter,resistor,switch"],
["Oscilloscope Introduction","Measurement","Explore an instrument in a simple source-load diagram.","acsource,oscilloscope,resistor,lamp"],
["Terminal Block Wiring","Panel","Use a terminal block as a named connection point.","battery,terminal,switch,lamp"],
["Switch Contact Study","Control","Experiment with a switch state in a load circuit.","battery,switch,lamp,resistor"],
["Two Load Comparison","DC Basics","Compare two different educational loads.","battery,switch,lamp,motor"],
["Relay and Buzzer","Industrial Control","Combine a protective device with relay and indicator.","battery,fuse,relay,buzzer"],
["Component Parameter Lab","Reference","Practise editing and comparing component parameters.","battery,resistor,capacitor,inductor"]
].map((x,i)=>({template:i+1,name:x[0],category:x[1],goal:x[2],types:x[3].split(",")}));
const variants=[["Starter",1],["Low Range",.5],["Standard Range",1.5],["High Range",2],["Troubleshooting",.8]];
const demos=templates.flatMap(t=>variants.map((v,i)=>({id:(t.template-1)*5+i+1,title:t.name+" · "+v[0],category:t.category,goal:t.goal,types:t.types,variant:v[0],factor:v[1],template:t.template})));
let selected=demos[0],query="",category="All";
function style(){if(document.getElementById("vpDemoStyle"))return;const st=document.createElement("style");st.id="vpDemoStyle";st.textContent=`
#vpDemoLibrary{position:fixed;inset:64px 14px 32px;background:#071321;color:#eaf5ff;border:1px solid #31516d;border-radius:14px;z-index:10000;display:none;grid-template-rows:auto 1fr;overflow:hidden;box-shadow:0 25px 80px #000b;font:13px system-ui}
#vpDemoLibrary.open{display:grid}.vpd-head{display:flex;align-items:center;gap:12px;padding:12px 16px;border-bottom:1px solid #29475f}.vpd-head b{color:#35d5ff;letter-spacing:.08em}.vpd-head button{margin-left:auto}.vpd-body{display:grid;grid-template-columns:minmax(250px,34%) 1fr;min-height:0}.vpd-side,.vpd-detail{padding:14px;overflow:auto;min-width:0}.vpd-side{border-right:1px solid #29475f}.vpd-side input,.vpd-btn{width:100%;padding:9px;margin-bottom:8px;background:#0b1b2c;color:#eaf5ff;border:1px solid #31516d;border-radius:7px;text-align:left;cursor:pointer}.vpd-btn.active,.vpd-btn:hover{border-color:#35d5ff}.vpd-side small{display:block;color:#8da4bd;margin-top:4px}.vpd-cats{display:flex;gap:5px;flex-wrap:wrap;margin:8px 0}.vpd-cats button{background:#102238;color:#a8bed3;border:1px solid #29475f;border-radius:6px;padding:6px;cursor:pointer}.vpd-detail h2{color:#35d5ff}.vpd-detail p{line-height:1.6;color:#b5c8d9}.vpd-detail .vpd-load{background:linear-gradient(135deg,#35d5ff,#65e6ad);color:#04131d;border:0;border-radius:8px;padding:10px 14px;font-weight:800;cursor:pointer}.vpd-note{border-left:3px solid #ffc45c;padding:8px 12px;background:#161c25;color:#d4c8a7}.vpd-list{max-height:calc(100% - 115px);overflow:auto}@media(max-width:720px){#vpDemoLibrary{inset:54px 4px 24px}.vpd-body{grid-template-columns:1fr;grid-template-rows:44% 56%}.vpd-side{border-right:0;border-bottom:1px solid #29475f;padding:9px}.vpd-detail{padding:10px}.vpd-head{padding:9px}.vpd-side input{margin-bottom:4px}}`;
document.head.appendChild(st)}
function open(){style();let root=document.getElementById("vpDemoLibrary");if(!root){root=document.createElement("section");root.id="vpDemoLibrary";document.body.appendChild(root)}draw();root.classList.add("open")}
function draw(){const root=document.getElementById("vpDemoLibrary");if(!root)return;const cats=["All",...new Set(demos.map(d=>d.category))],list=demos.filter(d=>(category==="All"||d.category===category)&&(d.title+" "+d.goal+" "+d.id).toLowerCase().includes(query.toLowerCase()));root.innerHTML='<header class="vpd-head"><b>VOLTPro · 100 GUIDED DEMO PROJECTS</b><span>'+list.length+' projects</span><button id="vpdClose" class="vpd-btn" style="width:auto;margin:0">Close</button></header><div class="vpd-body"><aside class="vpd-side"><input id="vpdSearch" placeholder="Search demos by name or topic"><div class="vpd-cats">'+cats.map(c=>'<button data-vpdcat="'+esc(c)+'">'+esc(c)+'</button>').join("")+'</div><div class="vpd-list">'+list.map(d=>'<button class="vpd-btn '+(selected.id===d.id?"active":"")+'" data-vpd="'+d.id+'"><b>'+String(d.id).padStart(3,"0")+'. '+esc(d.title)+'</b><small>'+esc(d.category)+'</small></button>').join("")+'</div></aside><main class="vpd-detail"><h2>'+esc(selected.title)+'</h2><p><b>Demo '+selected.id+' of 100 · '+esc(selected.category)+'</b></p><p>'+esc(selected.goal)+'</p><h3>Learning guide</h3><p>Place the listed components, trace each terminal-to-terminal connection, select components to edit their values, then run the educational analysis. Use Undo/Redo to compare changes.</p><h3>Included components</h3><p>'+selected.types.map(t=>esc((window.defs?.[t]||{}).name||t)).join(" → ")+'</p><p><b>Variant:</b> '+esc(selected.variant)+' · parameter factor '+selected.factor+'</p><div class="vpd-note">Educational example only. The demo wiring is a learning scaffold, not a validated electrical design or safety assessment.</div><p><button id="vpdLoad" class="vpd-load">Load demo into schematic</button></p></main></div>';
root.querySelector("#vpdClose").onclick=()=>root.classList.remove("open");root.querySelector("#vpdSearch").value=query;root.querySelector("#vpdSearch").oninput=e=>{query=e.target.value;draw()};root.querySelectorAll("[data-vpdcat]").forEach(b=>{if(b.dataset.vpdcat===category)b.classList.add("active");b.onclick=()=>{category=b.dataset.vpdcat;draw()}});root.querySelectorAll("[data-vpd]").forEach(b=>b.onclick=()=>{selected=demos.find(d=>d.id===Number(b.dataset.vpd))||demos[0];draw()});root.querySelector("#vpdLoad").onclick=()=>loadDemo(selected)}
function loadDemo(d){const S=window.S,defs=window.defs||{};if(!S)return;if(S.history){S.history.push(JSON.stringify({components:S.components,wires:S.wires}));if(S.history.length>30)S.history.shift();S.future=[]}const ids=d.types.map((t,i)=>"demo"+d.id+"_"+i),components=d.types.map((type,i)=>{const def=defs[type]||{},props=JSON.parse(JSON.stringify(def.props||{}));if(typeof props.voltage==="number")props.voltage=Math.max(1,Math.round(props.voltage*d.factor));if(typeof props.resistance==="number")props.resistance=Math.max(1,Math.round(props.resistance/d.factor));if(typeof props.rating==="number")props.rating=Math.max(.1,Math.round(props.rating*d.factor*10)/10);return{id:ids[i],type,x:120+i*150,y:210,rotation:0,props,pins:[]}}),wires=[];for(let i=0;i<components.length-1;i++){const a=components[i],b=components[i+1],last=Math.max(0,(defs[a.type]?.pins||2)-1);wires.push({id:"D"+d.id+"W"+(i+1),a:a.id+":"+last,b:b.id+":0"})}if(components.length>1){const last=components[components.length-1];wires.push({id:"D"+d.id+"W"+components.length,a:last.id+":"+Math.max(0,(defs[last.type]?.pins||2)-1),b:components[0].id+":0"})}S.components=components;S.wires=wires;S.selected=components[0]?.id||null;S.selectedWireId=null;S.mode="schematic";S.running=false;S.pan={x:0,y:0};S.zoom=1;window.VoltProUI?.render?.();document.querySelectorAll(".mode").forEach(b=>b.classList.toggle("active",b.dataset.mode==="schematic"));document.getElementById("vpDemoLibrary")?.classList.remove("open");const c=document.querySelector("#console");if(c)c.textContent+="\nLoaded demo "+d.id+": "+d.title+"\n"+d.goal}
window.VoltProDemoLibrary={open,demos:()=>demos.slice(),load:loadDemo};
document.addEventListener("keydown",e=>{if(e.key==="Escape")document.getElementById("vpDemoLibrary")?.classList.remove("open")});
})();