(()=>{"use strict";
const $=s=>document.querySelector(s);
function panel(title,body){let x=document.getElementById("vpPlatformPanel");if(!x){x=document.createElement("section");x.id="vpPlatformPanel";x.style.cssText="position:fixed;right:18px;top:78px;width:min(420px,calc(100vw - 36px));max-height:70vh;overflow:auto;background:#081522;color:#dcecff;border:1px solid #28506d;border-radius:12px;padding:16px;z-index:9999;box-shadow:0 20px 60px #0008;font:14px system-ui";document.body.appendChild(x)}x.innerHTML="<b>"+title+"</b><button id=vpClose style='float:right'>×</button><div style='margin-top:12px'>"+body+"</div>";$("#vpClose").onclick=()=>x.remove()}
function project(){return window.VoltProProject?.normalize({components:window.S?.components||[],wires:window.S?.wires||[]})||{components:[],wires:[]}}
function mount(){const bar=document.querySelector(".toolbar");if(!bar)return;
const items=[["Engineering","engineering"],["BOM","bom"],["Fault Lab","fault"],["Challenges","challenge"],["Tutorials","tutorial"],["MCU Lab","mcu"],["Accessibility","a11y"]];
for(const [label,id] of items){if(document.getElementById("vp-"+id))continue;const b=document.createElement("button");b.id="vp-"+id;b.textContent=label;b.onclick=()=>actions[id]();bar.appendChild(b)}
document.addEventListener("keydown",e=>{if(e.target.matches("input,textarea"))return;if(e.key==="Escape")document.getElementById("vpPlatformPanel")?.remove();if(e.key.toLowerCase()==="b")actions.bom();if(e.key.toLowerCase()==="f")actions.fault();});
}
const actions={
engineering(){panel("Engineering Toolkit",'<label>Load current (A) <input id=vpI type=number value=10></label><br><label>Length one-way (m) <input id=vpL type=number value=20></label><br><label>Voltage (V) <input id=vpV type=number value=230></label><br><label>Max drop (%) <input id=vpD type=number value=3></label><br><button id=vpCalc>Calculate cable</button><pre id=vpOut></pre>');$("#vpCalc").onclick=()=>{const r=VoltProEngineering.cableSize({current:+$("#vpI").value,length:+$("#vpL").value,voltage:+$("#vpV").value,maxDrop:+$("#vpD").value});$("#vpOut").textContent=JSON.stringify(r,null,2)}},
bom(){const rows=VoltProBOM.build(project(),Object.values(window.defs||{}).map((x,i)=>({id:Object.keys(window.defs||{})[i],name:x.name})));panel("Bill of Materials",'<button id=vpCsv>Export CSV</button><pre>'+rows.map(r=>r.reference+" | "+r.description+" | ×"+r.quantity).join("\n")+'</pre>');$("#vpCsv").onclick=()=>{const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([VoltProBOM.csv(rows)],{type:"text/csv"}));a.download="voltpro-bom.csv";a.click()}},
fault(){panel("Fault Laboratory",'<select id=vpFault>'+Object.entries(VoltProFaults.TYPES).map(([k,v])=>'<option value='+k+'>'+v.label+'</option>').join("")+'</select> <button id=vpApply>Apply</button><pre id=vpFaultOut></pre>');$("#vpApply").onclick=()=>{$("#vpFaultOut").textContent=JSON.stringify(VoltProFaults.analyze(VoltProFaults.apply(project(),{type:$("#vpFault").value,target:null})),null,2)}},
challenge(){const ch={id:"light-basic",title:"Build a protected light circuit",requiredComponents:["battery","switch","lamp"],rules:[{type:"connected",value:2}]};const r=VoltProChallenge.run(project(),ch);panel("Challenge: "+ch.title,"<h3>"+(r.passed?"PASSED":"NOT YET")+"</h3><p>"+r.message+"</p><p>Score: "+r.score+"/100</p>")},
tutorial(){const t={id:"first-circuit",title:"First circuit",steps:["Place a source.","Place a switch.","Place a load.","Wire the loop.","Run the analysis."]};let s=VoltProTutorial.session(t);const draw=()=>panel(t.title,"<p>Step "+(s.step+1)+" / "+t.steps.length+": "+(VoltProTutorial.current(s,t)||"Complete")+"</p><button id=vpNext>"+(s.complete?"Done":"Next")+"</button>");draw();$("#vpNext").onclick=()=>{VoltProTutorial.next(s,t);draw()}},
mcu(){panel("Microcontroller Lab",'<textarea id=vpCode rows=10 style="width:100%">void setup(){ pinMode(13, OUTPUT); Serial.println("VoltPRo"); }\nvoid loop(){ digitalWrite(13,HIGH); }</textarea><br><button id=vpRun>Simulate</button><pre id=vpMcuOut></pre>');$("#vpRun").onclick=()=>$("#vpMcuOut").textContent=JSON.stringify(VoltProMCU.simulate($("#vpCode").value,{target:"Arduino UNO"}),null,2)},
a11y(){document.documentElement.style.fontSize=document.documentElement.style.fontSize==="18px"?"":"18px";document.body.classList.toggle("vpHighContrast");panel("Accessibility","Keyboard shortcuts: B = BOM, F = Fault Lab, Escape = close panel. Font size toggle applied.")}};
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",mount);else mount();
})();