(()=>{"use strict";
const $=s=>document.querySelector(s);
const esc=x=>String(x??"").replace(/[&<>"]/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"}[m]));
const symbolLabel=x=>{const v=x?.symbol;if(typeof v==="string")return v==="generic"?"◇":v;if(v&&typeof v==="object")return String(v.label||v.text||v.name||v.id||"◇");return "◇"};
let catalog=[];
function ensureStyle(){
 if($("#vpWorkbenchStyle"))return;
 const s=document.createElement("style");s.id="vpWorkbenchStyle";s.textContent=`
#vpWorkbench{position:fixed;inset:72px 18px 42px 18px;background:#071321;border:1px solid #29475f;border-radius:14px;z-index:9000;display:none;grid-template-rows:auto 1fr;box-shadow:0 25px 80px #000b;overflow:hidden}
#vpWorkbench.open{display:grid}
.vpw-head{display:flex;align-items:center;gap:10px;padding:12px 14px;border-bottom:1px solid #29475f}
.vpw-head b{color:#35d5ff;font:800 12px ui-monospace,monospace;letter-spacing:.08em}.vpw-head span{color:#8da4bd;font-size:10px}
.vpw-head button{margin-left:auto;background:#102238;color:#eaf5ff;border:1px solid #31516d;border-radius:7px;padding:6px 10px;cursor:pointer}
.vpw-body{min-height:0;display:grid;grid-template-columns:235px 1fr}
.vpw-side{padding:12px;border-right:1px solid #29475f;overflow:auto}.vpw-side input{width:100%;background:#06101b;color:#eaf5ff;border:1px solid #29475f;border-radius:7px;padding:8px;margin-bottom:9px}
.vpw-cat{display:block;width:100%;text-align:left;background:#0b1b2c;color:#a8bed3;border:1px solid #213b53;border-radius:7px;padding:8px;margin:4px 0;cursor:pointer}.vpw-cat.active{color:#fff;border-color:#35d5ff}
.vpw-main{min-width:0;min-height:0;overflow:auto;padding:14px}.vpw-grid{display:grid;grid-template-columns:repeat(auto-fill,minmax(190px,1fr));gap:10px}
.vpw-card{background:#0b1a2b;border:1px solid #203b53;border-radius:10px;padding:10px;cursor:pointer}.vpw-card:hover{border-color:#35d5ff;transform:translateY(-1px)}
.vpw-symbol{height:64px;display:grid;place-items:center;background:#081624;border-radius:7px;color:#35d5ff;font:900 20px ui-monospace,monospace;margin-bottom:8px}.vpw-card b{font-size:11px}.vpw-card small{display:block;color:#8da4bd;font-size:9px;margin-top:3px}
.vpw-detail{display:none;background:#081a2b;border:1px solid #31516d;border-radius:10px;padding:14px;margin-bottom:12px}.vpw-detail.open{display:block}.vpw-detail h3{margin:0 0 8px;color:#35d5ff}.vpw-detail p{color:#a8bed3;font-size:10px;line-height:1.5}.vpw-detail code{color:#9fecc7}
.vpw-panel{display:grid;grid-template-columns:1fr 260px;gap:12px;height:100%}.vpw-rail{position:relative;min-height:320px;background:repeating-linear-gradient(0deg,#081522,#081522 31px,#0b1d2d 32px);border:1px solid #29475f;border-radius:10px;overflow:auto;padding:22px}
.vpw-rail-line{height:18px;background:#334b5e;border:1px solid #526d82;border-radius:3px;margin:115px 0 0}.vpw-device{position:absolute;top:55px;min-width:70px;height:105px;background:#d9e1e8;color:#071321;border:1px solid #8798a7;border-radius:4px;padding:7px 5px;text-align:center;font:800 9px system-ui;box-shadow:0 5px 15px #0007}.vpw-device small{display:block;font-weight:500;margin-top:7px}.vpw-sidebox{background:#081a2b;border:1px solid #29475f;border-radius:10px;padding:12px;color:#a8bed3;font-size:10px;overflow:auto}.vpw-sidebox h4{color:#35d5ff;margin:0 0 8px}
.vpw-panel-stage{min-width:0;overflow:auto;background:#06111d;border:1px solid #29475f;border-radius:10px;padding:12px}.vpw-enclosure{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:12px}.vpw-enclosure label,.vpw-sidebox label{display:flex;flex-direction:column;gap:4px;color:#8da4bd;font-size:10px}.vpw-enclosure input,.vpw-enclosure select,.vpw-sidebox input,.vpw-sidebox select{max-width:100%;background:#06101b;color:#eaf5ff;border:1px solid #31516d;border-radius:6px;padding:6px}.vpw-rails{display:grid;gap:14px;min-height:140px}.vpw-rail-row{min-width:0}.vpw-rail-title{color:#8da4bd;font:10px ui-monospace,monospace;margin-bottom:5px}.vpw-rail-title small{margin-left:8px}.vpw-rail-track{height:118px;position:relative;max-width:100%;overflow:visible;background:linear-gradient(180deg,transparent 45px,#526d82 46px,#334b5e 51px,#526d82 56px,transparent 57px);border-bottom:1px dashed #29475f}.vpw-rail-track:before{content:"";position:absolute;inset:0;background:repeating-linear-gradient(90deg,transparent 0,transparent 17px,#19364c 18px);pointer-events:none}.vpw-panel-device{position:absolute;top:10px;height:72px;z-index:2;overflow:hidden;background:#d9e1e8;color:#071321;border:1px solid #8798a7;border-radius:4px;padding:5px 2px;text-align:center;cursor:grab;touch-action:none;font:700 9px system-ui;box-shadow:0 4px 10px #0006}.vpw-panel-device:active{cursor:grabbing}.vpw-panel-device.selected{outline:2px solid #35d5ff;outline-offset:2px}.vpw-panel-device small{display:block;font-size:8px;font-weight:500;overflow-wrap:anywhere;margin-top:5px}.vpw-panel-actions{display:flex;flex-wrap:wrap;gap:6px;margin:10px 0}.vpw-panel-actions button,.vpw-sidebox>button{background:#102238;color:#eaf5ff;border:1px solid #31516d;border-radius:6px;padding:7px;cursor:pointer}.vpw-accessories{display:flex;flex-wrap:wrap;gap:6px}.vpw-accessory{background:#102238;border:1px solid #29475f;border-radius:5px;padding:5px;color:#8da4bd;font-size:9px}.vpw-validation{border:1px solid #31516d;border-radius:7px;padding:9px;overflow-wrap:anywhere}.vpw-validation.valid{border-color:#398b69}.vpw-validation.invalid{border-color:#bf665f}.vpw-validation p{margin:6px 0}.vpw-note{line-height:1.5;color:#8da4bd}.vpw-sidebox hr{border:0;border-top:1px solid #29475f;margin:12px 0}.vpw-plc{display:grid;grid-template-columns:220px 1fr;gap:12px}.vpw-logic-card{background:#0b1a2b;border:1px solid #29475f;border-radius:9px;padding:12px;margin-bottom:8px;color:#eaf5ff}.vpw-logic-card button{margin:4px;background:#102238;color:#fff;border:1px solid #31516d;border-radius:6px;padding:6px}.vpw-ladder{background:#06101b;border:1px solid #29475f;border-radius:10px;min-height:300px;padding:20px;font:11px/2 ui-monospace,monospace;color:#9fecc7}
@media(max-width:900px){#vpWorkbench{inset:58px 8px 30px 8px}.vpw-panel,.vpw-plc{grid-template-columns:1fr}.vpw-sidebox{max-height:220px;overflow:auto}}@media(max-width:760px){#vpWorkbench{inset:54px 5px 24px 5px;border-radius:10px}.vpw-head{padding:9px 10px}.vpw-head span{display:none}.vpw-body{grid-template-columns:1fr}.vpw-side{max-height:145px;border-right:0;border-bottom:1px solid #29475f}.vpw-main{padding:9px}.vpw-grid{grid-template-columns:repeat(auto-fill,minmax(150px,1fr));gap:7px}.vpw-card{padding:8px}.vpw-symbol{height:48px}.vpw-rail{min-height:300px;padding:12px;overflow:auto}.vpw-device{min-width:62px}.vpw-ladder{overflow:auto;white-space:pre;max-width:100%}}@media(max-width:430px){#vpWorkbench{inset:50px 3px 20px 3px}.vpw-grid{grid-template-columns:1fr 1fr}.vpw-head b{font-size:10px}.vpw-cat{padding:7px}.vpw-side input{padding:7px}}
`;document.head.appendChild(s);
}
function open(title,body){ensureStyle();let x=$("#vpWorkbench");if(!x){x=document.createElement("section");x.id="vpWorkbench";document.body.appendChild(x)}x.innerHTML='<div class="vpw-head"><b>'+esc(title)+'</b><span>FREE · LOCAL · NO SUBSCRIPTION</span><button id="vpwClose">Close</button></div><div class="vpw-body">'+body+'</div>';x.classList.add("open");$("#vpwClose").onclick=()=>x.classList.remove("open")}
async function loadCatalog(){if(catalog.length)return catalog;try{if(window.VoltProRegistry?.ready)await window.VoltProRegistry.ready;catalog=window.VoltProRegistry?.search?.("")||[];if(!catalog.length)catalog=await fetch("components.json",{cache:"no-store"}).then(r=>r.ok?r.json():Promise.reject()).then(x=>x.library||[])}catch{catalog=[]}return catalog}
function reference(){
 loadCatalog().then(items=>{let cat="All",q="";const draw=()=>{const cats=["All",...new Set(items.map(x=>x.category))];const filtered=items.filter(x=>(cat==="All"||x.category===cat)&&x.name.toLowerCase().includes(q.toLowerCase()));open("COMPONENT REFERENCE LIBRARY",'<aside class="vpw-side"><input id="vpwSearch" placeholder="Search 700+ components...">'+cats.map(c=>'<button class="vpw-cat '+(cat===c?"active":"")+'" data-c="'+esc(c)+'">'+esc(c)+'</button>').join("")+'</aside><main class="vpw-main"><div id="vpwDetail" class="vpw-detail"></div><div class="vpw-grid">'+filtered.map((x,i)=>'<article class="vpw-card" data-i="'+i+'"><div class="vpw-symbol">'+esc(symbolLabel(x))+'</div><b>'+esc(x.name)+'</b><small>'+esc(x.category||"Component")+'</small></article>').join("")+'</div></main>');$("#vpwSearch").value=q;$("#vpwSearch").oninput=e=>{q=e.target.value;draw()};document.querySelectorAll("[data-c]").forEach(b=>b.onclick=()=>{cat=b.dataset.c;draw()});document.querySelectorAll("[data-i]").forEach((c,i)=>c.onclick=()=>{const x=filtered[i],d=$("#vpwDetail");d.innerHTML="<h3>"+esc(x.name)+"</h3><p><b>Category:</b> "+esc(x.category)+"<br><b>Symbol:</b> "+esc(symbolLabel(x))+"<br><b>Model:</b> "+esc(x.electricalModel?.type||x.model||"catalog reference")+"<br><b>License:</b> VoltPRo original catalog entry. Verify third-party manufacturer assets before redistribution.</p>";d.classList.add("open")})};draw()})
}
function panel(){
 const api=window.VoltProPanel;if(!api){open("PANEL DESIGNER",'<main class="vpw-main">Panel layout module is unavailable. Reload the simulator and try again.</main>');return}
 const S=window.S||(window.S={components:[],wires:[]});S.panel=api.create(S.panel||{});
 let selected=null,drag=null;
 const supported=[["breaker","MCB / circuit breaker",36],["fuse","Fuse holder",18],["rcd","RCD / residual-current device",36],["contactor","Contactor",54],["relay","Control relay",36],["terminal","Terminal block",18],["ground","PE terminal",18],["switch","Switch / isolator",36],["socket","Panel socket",36],["acsource","AC supply device",36],["threephase","Three-phase supply device",54]];
 const available=()=>S.panel.items.filter(x=>x.railId===S.panel.rails[0]?.id);
 const freePosition=(railId,width)=>{const rail=S.panel.rails.find(r=>r.id===railId);if(!rail)return 0;for(let p=0;p+width<=rail.length*api.MODULE;p+=api.MODULE){if(!S.panel.items.some(x=>x.railId===railId&&p<x.position+x.width&&p+width>x.position))return p}return -1};
 const ensureRoom=width=>{let rail=S.panel.rails.find(r=>freePosition(r.id,width)>=0);if(!rail){api.addRail(S.panel,{length:18});rail=S.panel.rails[S.panel.rails.length-1]}return {rail,position:freePosition(rail.id,width)}};
 const syncDevices=()=>{for(const c of S.components){if(S.panel.items.some(x=>x.componentId===c.id))continue;const width=(supported.find(x=>x[0]===c.type)?.[2]||36),slot=ensureRoom(width);if(slot.position>=0)api.place(S.panel,{id:"P-"+c.id,componentId:c.id,type:c.type,label:c.props?.label||c.ref||c.id,ref:c.id,width,railId:slot.rail.id,position:slot.position,kind:"device"})}};
 const labelFor=x=>{const c=S.components.find(d=>d.id===x.componentId),def=window.defs?.[x.type]||window.VoltProRegistry?.definition?.(x.type)||{};return {name:def.name||x.type||"Panel accessory",symbol:def.symbol||x.type||"◇",component:c}};
 const validate=()=>api.validate(S.panel);
 function draw(){
  const v=validate(),item=S.panel.items.find(x=>x.id===selected)||null;
  const rails=S.panel.rails.map((r,ri)=>'<section class="vpw-rail-row"><div class="vpw-rail-title">'+esc(r.label||r.id)+' <small>'+esc(r.length)+' modules · '+esc(r.id)+'</small></div><div class="vpw-rail-track" data-rail-id="'+esc(r.id)+'" style="width:'+(Number(r.length||18)*api.MODULE+20)+'px">'+S.panel.items.filter(x=>x.railId===r.id).map(x=>{const d=labelFor(x);return '<button class="vpw-panel-device '+(x.id===selected?'selected':'')+'" data-panel-item="'+esc(x.id)+'" data-rail-id="'+esc(r.id)+'" style="left:'+(10+x.position)+'px;width:'+Math.max(18,x.width)+'px" title="'+esc(d.name+' · '+x.label)+'"><b>'+esc(x.label)+'</b><small>'+esc(d.name)+'</small></button>'}).join("")+'</div></section>').join("");
  const accessories=(S.panel.ducts||[]).map(d=>'<span class="vpw-accessory">Duct '+esc(d.id)+' · '+esc(Math.round((d.fill||0)*100))+'% fill</span>').concat((S.panel.terminalStrips||[]).map(t=>'<span class="vpw-accessory">'+esc(t.label||t.id)+' · '+esc(t.count)+' terminals</span>')).join("");
  open("PANEL DESIGNER · DIN RAIL WORKSPACE",'<main class="vpw-main" style="grid-column:1 / -1;min-width:0"><div class="vpw-panel"><section class="vpw-panel-stage"><div class="vpw-enclosure"><label>Enclosure label <input id="vpwEnclosureLabel" value="'+esc(S.panel.enclosure.label||"Main distribution board")+'"></label><label>IP rating <select id="vpwIpRating">'+["IP20","IP30","IP40","IP54","IP65"].map(x=>'<option '+((S.panel.enclosure.ipRating||"IP40")===x?"selected":"")+'>'+x+'</option>').join("")+'</select></label><label>Width (mm) <input id="vpwPanelWidth" type="number" min="150" max="2000" value="'+esc(S.panel.width)+'"></label><label>Height (mm) <input id="vpwPanelHeight" type="number" min="150" max="2000" value="'+esc(S.panel.height)+'"></label></div><div class="vpw-rails">'+rails+'</div><div class="vpw-panel-actions"><button id="vpwAddRail">+ DIN rail</button><button id="vpwAddDuct">+ Cable duct</button><button id="vpwAddStrip">+ Terminal strip</button></div><div class="vpw-accessories">'+accessories+'</div></section><aside class="vpw-sidebox"><h4>Device placement</h4><label>Supported device <select id="vpwDeviceType">'+supported.map(x=>'<option value="'+x[0]+'">'+esc(x[1])+'</option>').join("")+'</select></label><button id="vpwAddDevice">Add device to schematic + panel</button><p>Adding a device creates a schematic component and a physical panel placement. Drag a device across a rail to reposition it. Placements snap to 18 mm modules.</p><hr><h4>Selected placement</h4>'+(item?'<p><b>'+esc(item.type)+'</b> · '+esc(item.componentId||"Accessory")+'</p><label>Reference / label <input id="vpwItemLabel" value="'+esc(item.label)+'"></label><label>Width <select id="vpwItemWidth">'+[18,36,54,72,90].map(w=>'<option value="'+w+'" '+(Number(item.width)===w?"selected":"")+'>'+w/18+' module(s)</option>').join("")+'</select></label><button id="vpwRemovePlacement">Remove placement</button>': '<p>Select a device on the rail to edit its label or width.</p>')+'<hr><h4>Layout validation</h4><div class="vpw-validation '+(v.valid?"valid":"invalid")+'"><b>'+(v.valid?"No placement errors":"Layout needs attention")+'</b><p>'+v.errors.map(esc).concat(v.warnings.map(x=>"Warning: "+esc(x))).join("</p><p>")+'</p><small>'+v.deviceCount+' devices · '+v.railCount+' rails · '+v.modules+' occupied modules</small></div><p class="vpw-note">Panel layout is stored with the project. Verify enclosure dimensions, heat dissipation, clearances, protective devices and applicable standards before real installation.</p></aside></div></main>');
  $("#vpwEnclosureLabel").onchange=e=>{S.panel.enclosure.label=e.target.value};
  $("#vpwIpRating").onchange=e=>{S.panel.enclosure.ipRating=e.target.value};
  $("#vpwPanelWidth").onchange=e=>{S.panel.width=Math.max(150,Math.min(2000,+e.target.value||600))};
  $("#vpwPanelHeight").onchange=e=>{S.panel.height=Math.max(150,Math.min(2000,+e.target.value||400))};
  $("#vpwAddRail").onclick=()=>{api.addRail(S.panel,{length:18});draw()};
  $("#vpwAddDuct").onclick=()=>{const id="D"+(S.panel.ducts.length+1),duct=window.VoltProPanelAccessories?.duct?.({id,label:id,fill:.35})||{id,label:id,fill:.35};duct.label=id;S.panel.ducts.push(duct);draw()};
  $("#vpwAddStrip").onclick=()=>{const id="X"+(S.panel.terminalStrips.length+1),strip=window.VoltProPanelAccessories?.terminalStrip?.({id,label:id,count:12})||{id,label:id,count:12};S.panel.terminalStrips.push(strip);const slot=ensureRoom(36);if(slot.position>=0)api.place(S.panel,{id:"P-"+id,type:"terminal-strip",label:id+" terminal strip",width:36,railId:slot.rail.id,position:slot.position,kind:"accessory"});draw()};
  $("#vpwAddDevice").onclick=()=>{const type=$("#vpwDeviceType").value,def=window.defs?.[type]||window.VoltProRegistry?.definition?.(type)||{},before=S.components.length;window.VoltProUI?.addComponent?.(type,160+(before%5)*100,140+Math.floor(before/5)*80);const c=S.components[S.components.length-1];if(!c||S.components.length===before){return}const width=supported.find(x=>x[0]===type)?.[2]||36,slot=ensureRoom(width);if(slot.position<0){alert("No room on this rail. Add a DIN rail.");return}const id="P-"+c.id;api.place(S.panel,{id,componentId:c.id,type,label:c.props?.label||def.name||type,width,railId:slot.rail.id,position:slot.position,kind:"device"});selected=id;draw()};
  if(item){$("#vpwItemLabel").onchange=e=>{item.label=e.target.value.trim()||item.type;draw()};$("#vpwItemWidth").onchange=e=>{try{api.move(S.panel,item.id,{width:+e.target.value});draw()}catch(err){alert(err.message)}};$("#vpwRemovePlacement").onclick=()=>{api.remove(S.panel,item.id);selected=null;draw()}}
  document.querySelectorAll("[data-panel-item]").forEach(el=>{el.onclick=()=>{if(!drag?.moved){selected=el.dataset.panelItem;draw()}};el.onpointerdown=e=>{if(e.button!==0)return;selected=el.dataset.panelItem;const x=S.panel.items.find(z=>z.id===selected);drag={id:selected,pointerId:e.pointerId,startX:e.clientX,startPosition:x.position,railId:x.railId,moved:false};el.setPointerCapture?.(e.pointerId);e.preventDefault()};el.onpointermove=e=>{if(!drag||drag.pointerId!==e.pointerId)return;const target=document.elementFromPoint(e.clientX,e.clientY)?.closest?.(".vpw-rail-track[data-rail-id]");if(!target)return;const x=S.panel.items.find(z=>z.id===drag.id);if(!x)return;const rect=target.getBoundingClientRect(),position=Math.max(0,Math.round((e.clientX-rect.left-10)/api.MODULE)*api.MODULE);x.railId=target.dataset.railId;x.position=Math.min(position,Math.max(0,(Number(S.panel.rails.find(r=>r.id===x.railId)?.length||18)*api.MODULE)-x.width));drag.moved=true;el.style.left=(10+x.position)+"px";el.style.top="14px"};el.onpointerup=e=>{if(!drag||drag.pointerId!==e.pointerId)return;drag=null;draw()};el.onpointercancel=()=>{drag=null;draw()}})
 }
 syncDevices();draw();
}
function plc(){
 const io={i0:false,i1:false,i2:false,q0:false,q1:false};
 const draw=()=>{io.q0=io.i0&&!io.i1&&!io.i2;io.q1=io.q0;const state=io.i2?"EMERGENCY STOP ACTIVE":io.i1?"STOP PRESSED":io.q0?"MOTOR RUNNING":"READY · MOTOR OFF";const ladder="PLC LADDER LOGIC\n\n|----[ I0 START ]----[/ I1 STOP ]----[/ I2 E-STOP ]----( Q0 MOTOR )----|\n|-----------------------------------------------[ Q0 MOTOR ]----( Q1 LAMP )----|\n\nState: "+state+"\n\nInputs: I0="+(io.i0?"ON":"OFF")+" · I1="+(io.i1?"PRESSED":"RELEASED")+" · I2="+(io.i2?"ACTIVE":"SAFE")+"\nOutputs: Q0="+(io.q0?"ON":"OFF")+" · Q1="+(io.q1?"ON":"OFF")+"\n\nEducational logic only. No physical PLC is connected.";const el=$("#vpwLadder");if(el)el.textContent=ladder;document.querySelectorAll("[data-plc]").forEach(btn=>{const key=btn.dataset.plc;btn.classList.toggle("active",io[key]);btn.setAttribute("aria-pressed",String(io[key]));btn.textContent=(key==="i0"?"I0 Start":key==="i1"?"I1 Stop":"I2 E-Stop")+(io[key]?" · ACTIVE":"")})};
 open("PLC LOGIC LAB",'<aside class="vpw-side"><div class="vpw-logic-card"><b>Digital inputs</b><p>Toggle an input to see the ladder outputs update.</p><button data-plc="i0">I0 Start</button><button data-plc="i1">I1 Stop</button><button data-plc="i2">I2 E-Stop</button></div><div class="vpw-logic-card"><b>Calculated outputs</b><p>Q0 Motor: <strong id="vpwQ0">OFF</strong></p><p>Q1 Lamp: <strong id="vpwQ1">OFF</strong></p></div></aside><main class="vpw-main"><div class="vpw-ladder" id="vpwLadder"></div></main>');
 document.querySelectorAll("[data-plc]").forEach(btn=>btn.onclick=()=>{const key=btn.dataset.plc;io[key]=!io[key];draw();$("#vpwQ0").textContent=io.q0?"ON":"OFF";$("#vpwQ1").textContent=io.q1?"ON":"OFF";$("#vpwQ0").style.color=io.q0?"#65e6ad":"#8da4bd";$("#vpwQ1").style.color=io.q1?"#65e6ad":"#8da4bd"});
 draw();
}
function micro(){
 open("MICROCONTROLLER LAB",'<main class="vpw-main"><div class="vpw-logic-card"><b>Local educational sketch runner</b><p>Models a safe static subset of pinMode, digitalWrite and Serial print statements. It does not compile or upload firmware.</p><label>Board <select id="vpwBoard"><option>Arduino UNO</option><option>Generic GPIO</option></select></label></div><textarea id="vpwCode" rows="12" style="width:100%;margin:10px 0;background:#06101b;color:#eaf5ff;border:1px solid #31516d;border-radius:8px;padding:12px;font:12px/1.6 ui-monospace,monospace">void setup(){\n  pinMode(13, OUTPUT);\n  Serial.println("VoltPRo ready");\n}\nvoid loop(){\n  digitalWrite(13, HIGH);\n}</textarea><button id="vpwRunMcu">Run educational simulation</button><pre id="vpwMcuOut" style="white-space:pre-wrap;overflow-wrap:anywhere;background:#06101b;border:1px solid #29475f;border-radius:8px;padding:12px">Ready. Run the sketch to inspect modeled pin states.</pre></main>');
 $("#vpwRunMcu").onclick=()=>{const result=window.VoltProMCU?.simulate($("#vpwCode").value,{target:$("#vpwBoard").value});$("#vpwMcuOut").textContent=JSON.stringify(result||{error:"Microcontroller engine did not load."},null,2)};
}
function bind(){document.querySelectorAll(".mode").forEach(b=>b.addEventListener("click",()=>{if(b.dataset.mode==="reference")reference();else if(b.dataset.mode==="panel")panel();else if(b.dataset.mode==="plc")plc();else if(b.dataset.mode==="micro")micro();else if(b.dataset.mode==="schematic")document.querySelector("#vpWorkbench")?.classList.remove("open")}))}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",bind);else bind();
window.VoltProWorkbench={reference,panel,plc,micro};
})();